#! /bin/sh

LIST="${@}"

# does the command exist?
exists() {
    [ "$(command -v "${1}")" != "" ]
}

if ! exists clang-format; then
	echo 'no clang-format found, you need to install it' 1>&2
	exit 1
fi

if [ "${LIST}" = '' ]; then
	LIST="$(find . \
        '(' -type d '(' \
        -name libfirm -o -name googletest-src -o -name 'build*' -o -name 'external' ')' \
        -prune ')' \
        -o -type f '(' \
        -name '*.cc' -o -name '*.cpp' -o -name '*.cxx' -o \
        -name '*.c' -o \
        -name '*.hpp' -o -name '*.hdr' -o -name '*.hxx' -o -name '*.h' -o \
        -name '*.glsl' -o -name '*.vert' -o -name '*.frag' -o -name '*.comp' ')' -print)"
fi

format() {
    mv "${1}" "${1}".clangfmt_keep
    clang-format -style=file "${1}".clangfmt_keep > "${1}"
    diff "${1}".clangfmt_keep "${1}" 2>&1 > '/dev/null' && mv "${1}".clangfmt_keep "${1}"
}

echo "${LIST}" | while read i; do
    format "${i}" &
done

wait

exit 0
